import {Args, Query, Resolver} from '@nestjs/graphql';
import {LookupByFingerprintArgs} from './dto/lookup-by-fingerprint.dto';
import {RecordingArgs} from './dto/recording.args';
import {RecordingsArgs} from './dto/recordings.args';
import {RecordingConnection} from './models/recording-connection.model';
import {Recording} from './models/recording.model';

@Resolver()
export class RecordingResolver {
  /**
   * Musicbrainz Recording.
   */
  @Query(() => Recording)
  recording(@Args() args: RecordingArgs) {}

  /**
   * Musicbrainz Releases.
   */
  @Query(() => RecordingConnection)
  recordings(@Args() args: RecordingsArgs) {}

  /**
   * If you have an audio fingerprint generated by
   * [Chromaprint](https://acoustid.org/chromaprint), you can use this method
   * to lookup the MusicBrainz metadata associated with this fingerprint.
   */
  @Query(() => RecordingConnection)
  lookupByFingerprint(@Args() args: LookupByFingerprintArgs) {}
}
